<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE plytoteka [
<!ELEMENT plytoteka (album*)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT wykonawca (#PCDATA)>
<!ELEMENT album (tytul, wykonawca,nagrania)>
<!ELEMENT nagrania (tytul+)>
]>
<plytoteka>
<album>
<tytul>Bal Wszystkich Świętych</tytul>
<wykonawca>Budka Suflera</wykonawca>
<nagrania>
<tytul>Takie Tango</tytul>
<tytul>Moje Radio</tytul>
</nagrania>
</album>
</plytoteka>